### ISSUE TITLE
Russian localized error

### ISSUE THREAD

**Issue by VadimAzure** [Mutagen-Modding/Mutagen#348] opened 2022-07-23 07:55 UTC
Hello, the bad translation problem is back again.
![image](https://user-images.githubusercontent.com/55535590/180595986-a9e49cdc-b0b3-485d-bf8d-eaec08acd0c1.png)
![image](https://user-images.githubusercontent.com/55535590/180596043-7d4cbc0e-8db8-4565-acab-8d2c1de0fdab.png)
![image](https://user-images.githubusercontent.com/55535590/180596072-b8ec50fe-cb89-4cb8-80b8-ea191e6e567b.png)
Previously, it was solved through the setting, but it no longer works or is bad.
![image](https://user-images.githubusercontent.com/55535590/180596111-804532fa-533f-4d16-b2bf-0763b5fce281.png)

**Comment by Noggog** [comment] 2022-07-25 14:03
Duplicate of https://github.com/Mutagen-Modding/Synthesis/issues/344

**Closed as completed by Noggog** 2022-07-25 14:03 UTC
